Add Fetchers
apmath-web/applications pull request #20
Opened 2019-05-27 23:49 UTC by Evolyuta

- [ ] Add Abstract fetcher
- [ ]Add Clients fetcher
- [ ]Add Expenses fetcher
- [ ]Add Interests fetcher
- [ ] Delete old fetchers
- [ ] Change imports

2019-05-28 19:11 UTC, malinink requested changes

2019-05-28 19:11 UTC, malinink commented on src/com/apmath/applications/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun isSuccess(path: String): Boolean {
этот функционал нужен? для чего используется?

2019-05-28 19:18 UTC, Evolyuta commented on src/com/apmath/applications/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun isSuccess(path: String): Boolean {
для проверки проверки в сервисе существования ClientId при работе ClientFetcher 
![Screenshot from 2019-05-29 01-16-55](https://user-images.githubusercontent.com/22666053/58505740-4ab58b80-8196-11e9-8017-96a93713d253.png)
![Screenshot from 2019-05-29 01-18-21](https://user-images.githubusercontent.com/22666053/58505797-72a4ef00-8196-11e9-8f20-124af68ccf69.png)
![Screenshot from 2019-05-29 01-18-25](https://user-images.githubusercontent.com/22666053/58505798-72a4ef00-8196-11e9-938a-8c3718cd27de.png)

2019-05-28 20:04 UTC, malinink commented on src/com/apmath/applications/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun isSuccess(path: String): Boolean {
очень неочевидно что это должен быть всегда гет, и что он делает тоже не очень очевидно

2019-05-28 20:05 UTC, malinink commented on src/com/apmath/applications/infrastructure/fetchers/AbstractFetcher.kt
> +    suspend inline fun isSuccess(path: String): Boolean {
может быть сделать обертку над обычным гетом? т.е. пусть exists дергает гет, и всего делов

2019-05-29 05:54 UTC, malinink commented on src/com/apmath/applications/infrastructure/fetchers/ClientsFetcher.kt
> +    suspend fun getClient (request: Int): HttpResponse {
может быть всёже `clientId` а не `request` ?

2019-05-29 06:18 UTC, malinink approved these changes

2019-05-29 06:19 UTC, merged