Create add method in service
apmath-web/applications pull request #30
Opened 2019-05-30 13:16 UTC by Evolyuta

- [ ] fill add method

- [ ] add NoClientException

- [ ] link BL and API exceptions

2019-05-30 20:30 UTC, malinink requested changes

2019-05-30 20:30 UTC, malinink commented on src/com/apmath/applications/domain/exceptions/NoClientException.kt
> +class NoClientException : Exception()
EOF

2019-05-30 20:30 UTC, malinink commented on src/com/apmath/applications/domain/services/ApplicationService.kt
> +        when {
в чем смысл все пихать в else блок?
выбросьте exception в if блоке, и далее реализуйле свою логику

2019-05-30 20:30 UTC, malinink commented on src/com/apmath/applications/domain/services/ApplicationService.kt
> +        val clientsResult = GlobalScope.async {
без GS никак?

2019-05-31 13:30 UTC, Evolyuta commented on src/com/apmath/applications/domain/services/ApplicationService.kt
> +        val clientsResult = GlobalScope.async {
попробовал с coroutineScope и не получилось, можно GlobalScope оставить?

2019-05-31 13:48 UTC, malinink requested changes

2019-05-31 13:48 UTC, malinink commented on src/com/apmath/applications/domain/services/ApplicationService.kt
> +        val clientsResult = GlobalScope.async {
Поставьте внутьрь TODO на ресерч, я при случае гляну, ощущение что это не совсем коррекное решение

2019-05-31 13:51 UTC, malinink approved these changes

2019-05-31 13:51 UTC, merged